<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.1.0"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.1.0"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.0"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.0"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.1.0"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="RestSharp" Version="112.1.1-alpha.0.4" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Windows\MainWindow.axaml.cs">
        <DependentUpon>MainWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <Content Include="Assets\Icons\Inferyn_Icon.ico">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Assets\Fonts\JetBrainsMono-Bold.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMono-Bold.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMono-BoldItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMono-BoldItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMono-ExtraBold.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMono-ExtraBold.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMono-ExtraBoldItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMono-ExtraBoldItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMono-ExtraLight.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMono-ExtraLight.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMono-ExtraLightItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMono-ExtraLightItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMono-Italic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMono-Italic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMono-Light.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMono-Light.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMono-LightItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMono-LightItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMono-Medium.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMono-Medium.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMono-MediumItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMono-MediumItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMono-Regular.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMono-Regular.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMono-SemiBold.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMono-SemiBold.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMono-SemiBoldItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMono-SemiBoldItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMono-Thin.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMono-Thin.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMono-ThinItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMono-ThinItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMonoNL-Bold.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMonoNL-Bold.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMonoNL-BoldItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMonoNL-BoldItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMonoNL-ExtraBold.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMonoNL-ExtraBold.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMonoNL-ExtraBoldItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMonoNL-ExtraBoldItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMonoNL-ExtraLight.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMonoNL-ExtraLight.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMonoNL-ExtraLightItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMonoNL-ExtraLightItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMonoNL-Italic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMonoNL-Italic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMonoNL-Light.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMonoNL-Light.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMonoNL-LightItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMonoNL-LightItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMonoNL-Medium.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMonoNL-Medium.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMonoNL-MediumItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMonoNL-MediumItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMonoNL-Regular.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMonoNL-Regular.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMonoNL-SemiBold.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMonoNL-SemiBold.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMonoNL-SemiBoldItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMonoNL-SemiBoldItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMonoNL-Thin.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMonoNL-Thin.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\JetBrainsMonoNL-ThinItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\JetBrainsMonoNL-ThinItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Icons\Inferyn.ico" />
      <None Include="Assets\Icons\inferyn.png" />
      <None Remove="Assets\Fonts\Inter_18pt-Black.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_18pt-Black.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_18pt-BlackItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_18pt-BlackItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_18pt-Bold.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_18pt-Bold.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_18pt-BoldItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_18pt-BoldItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_18pt-ExtraBold.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_18pt-ExtraBold.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_18pt-ExtraBoldItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_18pt-ExtraBoldItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_18pt-ExtraLight.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_18pt-ExtraLight.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_18pt-ExtraLightItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_18pt-ExtraLightItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_18pt-Italic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_18pt-Italic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_18pt-Light.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_18pt-Light.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_18pt-LightItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_18pt-LightItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_18pt-Medium.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_18pt-Medium.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_18pt-MediumItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_18pt-MediumItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_18pt-Regular.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_18pt-Regular.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_18pt-SemiBold.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_18pt-SemiBold.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_18pt-SemiBoldItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_18pt-SemiBoldItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_18pt-Thin.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_18pt-Thin.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_18pt-ThinItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_18pt-ThinItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_24pt-Black.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_24pt-Black.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_24pt-BlackItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_24pt-BlackItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_24pt-Bold.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_24pt-Bold.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_24pt-BoldItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_24pt-BoldItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_24pt-ExtraBold.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_24pt-ExtraBold.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_24pt-ExtraBoldItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_24pt-ExtraBoldItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_24pt-ExtraLight.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_24pt-ExtraLight.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_24pt-ExtraLightItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_24pt-ExtraLightItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_24pt-Italic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_24pt-Italic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_24pt-Light.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_24pt-Light.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_24pt-LightItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_24pt-LightItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_24pt-Medium.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_24pt-Medium.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_24pt-MediumItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_24pt-MediumItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_24pt-Regular.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_24pt-Regular.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_24pt-SemiBold.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_24pt-SemiBold.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_24pt-SemiBoldItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_24pt-SemiBoldItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_24pt-Thin.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_24pt-Thin.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_24pt-ThinItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_24pt-ThinItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_28pt-Black.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_28pt-Black.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_28pt-BlackItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_28pt-BlackItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_28pt-Bold.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_28pt-Bold.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_28pt-BoldItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_28pt-BoldItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_28pt-ExtraBold.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_28pt-ExtraBold.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_28pt-ExtraBoldItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_28pt-ExtraBoldItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_28pt-ExtraLight.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_28pt-ExtraLight.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_28pt-ExtraLightItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_28pt-ExtraLightItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_28pt-Italic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_28pt-Italic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_28pt-Light.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_28pt-Light.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_28pt-LightItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_28pt-LightItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_28pt-Medium.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_28pt-Medium.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_28pt-MediumItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_28pt-MediumItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_28pt-Regular.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_28pt-Regular.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_28pt-SemiBold.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_28pt-SemiBold.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_28pt-SemiBoldItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_28pt-SemiBoldItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_28pt-Thin.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_28pt-Thin.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <None Remove="Assets\Fonts\Inter_28pt-ThinItalic.ttf" />
      <AvaloniaResource Include="Assets\Fonts\Inter_28pt-ThinItalic.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
    </ItemGroup>

    <ItemGroup>
      <None Remove="VERSION" />
      <AvaloniaResource Include="Assets\Icons\Inferyn.ico">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
      <Content Include="Assets\Icons\Inferyn.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="VERSION">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Assets\Icons\Inferyn.png" />
      <None Remove="LICENSE" />
      <Content Include="LICENSE">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Assets\Images\Backgrounds\inferyn_large_1.png" />
      <Content Include="Assets\Images\Backgrounds\inferyn_large_1.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>
</Project>
